ezsystems/ezplatform-demo

- ezpublish/Resources/views/full/home_page.html.twig
- ezpublish/Resources/views/pagelayout_footer.html.twig
- ezpublish/config/config.yml
- ezpublish/config/default_parameters.yml
Fixed Contact Us url on button 'Get in touch!' in footer
https://jira.ez.no/browse/EZP-25274
> EZP-25274: "Get in Touch" Button (footer) is not working

- README.md
Link to Jira task: https://jira.ez.no/browse/EZP-25284
Image included in README:
> EZP-25274: Update README of ezplatform-demo repository

- src/AppBundle/Resources/installer/sql/app_data.sql
**JIRA ticket related:** https://jira.ez.no/browse/EZP-25522
> EZP-25522: User is not able to get variation of his profile image

- app/Resources/views/full/blog.html.twig
- app/Resources/views/full/blog_post.html.twig
- app/Resources/views/full/contact_form.html.twig
- app/Resources/views/full/contact_form_submitted.html.twig
- app/Resources/views/full/gallery.html.twig
- app/Resources/views/full/home_page.html.twig
- app/config/views.yml
> Integrates feature added in https://github.com/ezsystems/ezpublish-kernel/pull/1626
Tested manually.
> EZP-25627: Integrated pagelayout configuration feature in platform demo

- behat.yml.dist
> Implements https://jira.ez.no/browse/EZP-25829
> Status: Ready for review
Ref: https://github.com/ezsystems/ezplatform/commit/f82fa586ddc53a33ef6c699e05c1233346767b5b
This was done in Platform, should be done in Platform-demo too.
Ping @bdunogier @andrerom
> Fix EZP-25829: EzBehatExtension should be activated in Platform demo

- .travis.yml
- bin/.ci/docker_hub_push.sh
- composer.lock
> [Docker] Setup deployment of demo docker image

- .platform.app.yaml
Open question: Is the lock file approach sufficient?
> Run the CLI installer, but only if it hasn't been run

- .platform.app.yaml
- .platform/services.yaml
- app/config/parameters_platform.php
- enable Redis
- Use MariaDB 10.0 instead of Mysql 5.5
- add readline php ext
ping @Crell *Note: Besides review and tests, could you check if port number in any cases is different than standard 6379? If so will need to add parameters for this.*
> [Platform.sh] Add Redis, mariadb 10.0 & readline php ext

- app/config/parameters_platform.php
One little comma can cause a lot of trouble. :smile:
> Fix syntax error in parameters_platform.php

- app/Resources/views/full/blog_post.html.twig
- app/Resources/views/home/blog_post.html.twig
- app/Resources/views/line/blog_post.html.twig
Link to Jira task: https://jira.ez.no/browse/EZP-26045
> EZP-26045: Error 500 on Preview in Content Edit mode

- app/Resources/views/pagelayout.html.twig
- app/Resources/views/pagelayout_header.html.twig
- app/Resources/views/pagelayout_styles.html.twig
- app/Resources/views/pagelayout_user_menu.html.twig
- app/Resources/views/user/registration_confirmation.html.twig
- app/Resources/views/user/registration_content_form.html.twig
- app/Resources/views/user/registration_form.html.twig
- app/config/views.yml
- src/AppBundle/Resources/installer/sql/app_data.sql
- web/assets/css/style.css
https://jira.ez.no/browse/EZP-26037
Registration form + user menu:
Confirmation page:
> EZP-26037: As an user, I want to be able to register

- app/Resources/views/user/login.html.twig
- app/config/views.yml
- web/assets/css/style.css
https://jira.ez.no/browse/EZP-26038
Review after merge of #37.
> EZP-26038: As an user, I want to be able to log in

- app/Resources/views/user/login.html.twig
Behat tests are failing after merging https://github.com/ezsystems/ezplatform-demo/commit/e097a0d90a06e98a24a57f1f2b65bb896f67893d
> Fix failing Behat tests after implementing Login feature

- README.md
- app/config/parameters.yml.dist
- Use doctrine command to create the database directly in bash
- rename default database name to fit the project and remove confilt with ezplatform installation
https://jira.ez.no/browse/DEMO-46
> DEMO-46: Use symfony command during install

- app/Resources/views/themes/tastefulplanet/full/home.html.twig
- web/assets/css/home.css
jira issue: https://jira.ez.no/browse/DEMO-138
> DEMO-138: Home Page CSS improvements

- src/AppBundle/MigrationVersions/all.yml
jira issue: https://jira.ez.no/browse/DEMO-137
> DEMO-137: update migration file to match the new design

- app/config/default_parameters.yml
jira issue: https://jira.ez.no/browse/DEMO-120
> DEMO-120: Added place_list Content Type to top menu

- app/Resources/views/themes/tastefulplanet/full/contact_form_submitted.html.twig
- app/Resources/views/themes/tastefulplanet/full/subscribe.html.twig
- app/Resources/views/themes/tastefulplanet/layout/header.html.twig
- app/Resources/views/themes/tastefulplanet/mail/contact.html.twig
- app/config/default_parameters.yml
- app/config/ezplatform.yml
- app/config/routing.yml
- app/config/services.yml
- app/config/views.yml
- src/AppBundle/Controller/ContactFormController.php
- src/AppBundle/Controller/MenuController.php
- src/AppBundle/Form/Type/ContactType.php
- src/AppBundle/Mail/Sender.php
- src/AppBundle/Model/Contact.php
- web/assets/css/subscribe.css
jira issue: https://jira.ez.no/browse/DEMO-141
> DEMO-141: Subscribe Full View

- app/Resources/NetgenTagsBundle/views/tag/view.html.twig
- app/Resources/views/themes/admin/fields/eztags_field.html.twig
- app/Resources/views/themes/tastefulplanet/full/article.html.twig
- app/Resources/views/themes/tastefulplanet/full/blog_post.html.twig
- app/Resources/views/themes/tastefulplanet/full/place.html.twig
- app/Resources/views/themes/tastefulplanet/search_result_item/article.html.twig
- app/Resources/views/themes/tastefulplanet/search_result_item/place.html.twig
- app/Resources/views/themes/tastefulplanet/search_result_item/product.html.twig
- app/config/ezplatform.yml
- app/config/views.yml
- web/assets/css/tags.css
jira issue: https://jira.ez.no/browse/DEMO-150
> DEMO-150: Add eZ Tags view

- app/AppKernel.php
- app/Resources/views/themes/tastefulplanet/pagelayout.html.twig
- app/config/ezplatform.yml
- app/config/routing.yml
- composer.json
- src/AppBundle/MigrationVersions/all.yml
- src/AppBundle/MigrationVersions/product_list.yml
> Nova seo bundle

- app/Resources/views/themes/tastefulplanet/card/product.html.twig
- app/Resources/views/themes/tastefulplanet/full/product_list.html.twig
- app/config/default_parameters.yml
- app/config/ezplatform.yml
- app/config/image_variations.yml
- app/config/services.yml
- app/config/views.yml
- src/AppBundle/Controller/ProductListController.php
- src/AppBundle/Entity/ProductSearch.php
- src/AppBundle/Form/Type/ProductSearchType.php
- web/assets/css/product_list.css
https://jira.ez.no/browse/DEMO-113
> DEMO-113: [Product] - Card View

- app/config/ezplatform.yml
https://jira.ez.no/browse/EZP-29047
> EZP-29047: Youtube custom tag not rending on the front-end

- app/Resources/views/themes/tastefulplanet/fields/ezrichtext/custom_tags/ezyoutube.html.twig
- app/config/services.yml
- src/AppBundle/Twig/YoutubeIdExtractorExtension.php
- tests/AppBundle/Twig/YoutubeIdExtractorExtensionTest.php
https://jira.ez.no/browse/DEMO-155
> DEMO-155: Improve youtube custom tag with a better URL support

- src/AppBundle/MigrationVersions/all.yml
https://jira.ez.no/browse/DEMO-168
> DEMO-168: Video content type uses incorrect fieldtype for video files

- web/assets/css/tastefulplanet.css
jira issue: https://jira.ez.no/browse/DEMO-172
> DEMO-172: image alignments for the new design

- app/AppKernel.php
- app/config/config.yml
- app/config/default_parameters.yml
- composer.json
https://jira.ez.no/browse/DEMO-159
requires: 
https://github.com/ezsystems/ezplatform-automated-translation/pull/4  (merged)
https://github.com/ezsystems/ezplatform-automated-translation/pull/5
> DEMO-159: Added ezplatform-automated-translation bundle

- .travis.yml
- bin/.travis/trusty/setup_ezplatform.sh
- tests/AppBundle/Behat/PlatformDemoEnvironmentConstants.php
Adding `PlatformDemoEnvironmentConstants` class.
JIRA: https://jira.ez.no/browse/EZP-29143
> EZP-29143 run test features on Demo version without changing feature files

- app/config/views.yml
- src/AppBundle/QueryType/ChildrenQueryType.php
https://jira.ez.no/browse/DEMO-194
required by: https://github.com/ezsystems/ezplatform-ee-demo/pull/80
> DEMO-194: Query Type

- web/assets/scss/_article.scss
- web/assets/scss/_place.scss
https://jira.ez.no/browse/DEMO-186
> DEMO-183: Image for Mexican Cuisine has different size on tablets

- app/Resources/views/themes/tastefulplanet/layout/header.html.twig
- web/assets/scss/_header.scss
https://jira.ez.no/browse/DEMO-188
> DEMO-188: Different vertical align for Languages and Administrator

- web/assets/scss/_header.scss
> Demo 205 social icons aligment

- app/Resources/views/themes/tastefulplanet/full/home.html.twig
- web/assets/scss/_folder.scss
- web/assets/scss/_home.scss
- web/assets/scss/_place.list.scss
- web/assets/scss/_place.scss
https://jira.ez.no/browse/DEMO-251
> DEMO-251: eZ Platform OE demo improvements

- app/Resources/views/themes/tastefulplanet/card/product.html.twig
- web/assets/scss/_product.list.scss
https://jira.ez.no/browse/DEMO-264
> DEMO-264:Fix height for the product cards

- app/Resources/views/themes/tastefulplanet/layout/header.html.twig
- web/assets/scss/_header.scss
https://jira.ez.no/browse/DEMO-272
> DEMO-272: Add expanding menu item "MORE" for the top menu

- app/config/default_parameters.yml
- app/config/services/migration.yml
- app/config/views.yml
- src/AppBundle/Migration/FieldHandler/EzImageAsset.php
- src/AppBundle/MigrationVersions/all.yml
- src/AppBundle/MigrationVersions/content.yml
- src/AppBundle/MigrationVersions/product_list.yml
https://jira.ez.no/browse/DEMO-255
> DEMO-255: Replace `image` field type with `Image Asset` field type - blog post

- app/Resources/views/themes/tastefulplanet/line/blog_post.html.twig
https://jira.ez.no/browse/DEMO-284
> DEMO-284: 500 error when opening /Blog after creating a new blog post

- app/Resources/EzPlatformUserBundle/views/change_password/index.html.twig
- app/Resources/EzPlatformUserBundle/views/change_password/success.html.twig
- app/Resources/views/themes/tastefulplanet/layout/header.html.twig
- app/config/services.yml
- app/config/services/controllers.yml
- src/AppBundle/MigrationVersions/users.yml
- web/assets/scss/_forms.scss
- web/assets/scss/_header.scss
- web/assets/scss/demo.scss
https://jira.ez.no/browse/DEMO-163
> DEMO-163: As a visitor I want to change my password

- app/Resources/EzPlatformUserBundle/views/forgot_password/index.html.twig
- app/Resources/EzPlatformUserBundle/views/forgot_password/success.html.twig
- app/Resources/EzPlatformUserBundle/views/forgot_password/with_login.html.twig
- app/Resources/EzPlatformUserBundle/views/reset_password/index.html.twig
- app/Resources/EzPlatformUserBundle/views/reset_password/invalid_link.html.twig
- app/Resources/EzPlatformUserBundle/views/reset_password/success.html.twig
- app/Resources/views/themes/tastefulplanet/user/login.html.twig
https://jira.ez.no/browse/DEMO-162
> DEMO-162: As a visitor I want to reset my password

- assets/scss/_carousel.scss
- templates/themes/maison/full/inspiration_list.html.twig
- templates/themes/maison/menu/inspirations-menu.html.twig
Add css and template changes for Inspiration List / Inspiration Page / Menu carousel
> Changes for inspirations

- config/packages/ezplatform.yaml
- config/packages/views.yaml
- src/MigrationVersions/users.yaml
- templates/themes/professionals/full/home.html.twig
- templates/themes/professionals/layout/footer.html.twig
- templates/themes/professionals/layout/header.html.twig
https://jira.ez.no/browse/DEMO-324
> DEMO-324: Prepare multi-site configuration
